[package]
name = "bevy_game_template"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"
bevy-inspector-egui = "0.21.0"
bevy_common_assets = { version = "0.8.0", features = ["ron"] }
serde = "*"
